<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="objects\types\in\" />
    <Folder Include="objects\types\out\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.Compiler.CO.CT\ZSharp.Compiler.CO.CT.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.CO.RT\ZSharp.Compiler.CO.RT.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.ILLoader.Attributes\ZSharp.Compiler.ILLoader.Attributes.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.TS.Static\ZSharp.Compiler.TS.Static.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler\ZSharp.Compiler.csproj" />
    <ProjectReference Include="..\ZSharp.Runtime\ZSharp.Runtime.csproj" />
  </ItemGroup>

</Project>
