<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ZSharp.SourceCompiler</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.AST\ZSharp.AST.csproj" />
    <ProjectReference Include="..\ZSharp.Interpreter\ZSharp.Interpreter.csproj" />
  </ItemGroup>

</Project>
