<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.Compiler.Core\ZSharp.Compiler.Core.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.ILLoader\ZSharp.Compiler.ILLoader.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.IR\ZSharp.Compiler.IR.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler\ZSharp.Compiler.csproj" />
    <ProjectReference Include="..\ZSharp.IR\ZSharp.IR.csproj" />
    <ProjectReference Include="..\ZSharp.Runtime\ZSharp.Runtime.csproj" />
  </ItemGroup>

</Project>
