<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.AST\ZSharp.AST.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.CG.Proxy\ZSharp.Compiler.CG.Proxy.csproj" />
    <ProjectReference Include="..\ZSharp.HIR.Code\ZSharp.HIR.Code.csproj" />
    <ProjectReference Include="..\ZSharp.SourceCompiler.Common\ZSharp.SourceCompiler.Common.csproj" />
    <ProjectReference Include="..\ZSharp.SourceCompiler.Core\ZSharp.SourceCompiler.Core.csproj" />
    <ProjectReference Include="..\ZSharp.SourceCompiler.Module\ZSharp.SourceCompiler.Module.csproj" />
  </ItemGroup>

</Project>
