<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Package.DotNet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="definitions\modifiers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.HIR\ZSharp.HIR.csproj" />
  </ItemGroup>

</Project>
