<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />

  <ItemGroup>
    <ProjectReference Include="..\CommonZ\CommonZ.csproj" />
    <ProjectReference Include="..\ZSharp.AST\ZSharp.AST.csproj" />
    <ProjectReference Include="..\ZSharp.Tokenizer\ZSharp.Tokenizer.csproj" />
  </ItemGroup>

</Project>
