<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.Compiler.Core\ZSharp.Compiler.Core.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.Evaluation\ZSharp.Compiler.Evaluation.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler\ZSharp.Compiler.csproj" />
    <ProjectReference Include="..\ZSharp.Importer.RT\ZSharp.Importer.RT.csproj" />
    <ProjectReference Include="..\ZSharp.Platform.Runtime\ZSharp.Platform.Runtime.csproj" />
  </ItemGroup>

</Project>
