<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="objects\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.Compiler.ILLoader.Attributes\ZSharp.Compiler.ILLoader.Attributes.csproj" />
    <ProjectReference Include="..\ZSharp.CT.StandardLibrary.FileSystem\ZSharp.CT.StandardLibrary.FileSystem.csproj" />
    <ProjectReference Include="..\ZSharp.Interpreter\ZSharp.Interpreter.csproj" />
  </ItemGroup>

</Project>
