<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="core\type system\**" />
    <EmbeddedResource Remove="core\type system\**" />
    <None Remove="core\type system\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.Compiler.CG\ZSharp.Compiler.CG.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.Context\ZSharp.Compiler.Context.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.Core\ZSharp.Compiler.Core.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.Evaluation\ZSharp.Compiler.Evaluation.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.IR\ZSharp.Compiler.IR.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.Overloading\ZSharp.Compiler.Overloading.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.Reflection\ZSharp.Compiler.Reflection.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.TS\ZSharp.Compiler.TS.csproj" />
    <ProjectReference Include="..\ZSharp.IR\ZSharp.IR.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.IR\ZSharp.IR.csproj" />
    <ProjectReference Include="..\ZSharp.Logging\ZSharp.Logging.csproj" />
  </ItemGroup>

</Project>
