<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Package.ZSharp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.HIR\ZSharp.HIR.csproj" />
  </ItemGroup>

</Project>
