<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="old\**" />
    <EmbeddedResource Remove="old\**" />
    <None Remove="old\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.AST\ZSharp.AST.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.CO.CT\ZSharp.Compiler.CO.CT.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.CO.RT\ZSharp.Compiler.CO.RT.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.Core\ZSharp.Compiler.Core.csproj" />
    <ProjectReference Include="..\ZSharp.Compiler.TS.Static\ZSharp.Compiler.TS.Static.csproj" />
    <ProjectReference Include="..\ZSharp.SourceCompiler.Common\ZSharp.SourceCompiler.Common.csproj" />
    <ProjectReference Include="..\ZSharp.SourceCompiler.Core\ZSharp.SourceCompiler.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="objects\functional\parameter\" />
    <Folder Include="objects\functional\signature\" />
    <Folder Include="objects\oop\" />
  </ItemGroup>

</Project>
