<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZSharp.Interpreter\ZSharp.Interpreter.csproj" />
    <ProjectReference Include="..\ZSharp.SourceCompiler.Project\ZSharp.SourceCompiler.Project.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="test-projects\" />
  </ItemGroup>

</Project>
